### ISSUE TITLE
Add support for ePub 3.0 "Media Overlays"

### ISSUE THREAD

**Issue by kjantzer** [FolioReader/FolioReaderKit#11]
Particularly, the ability to sync audio to text.

>EPUB Media Overlays 3.0 ... [supports] representation of audio synchronized with the EPUB Content Document.  [[source]](http://www.idpf.org/epub/30/spec/epub30-mediaoverlays.html#sec-overview-purpose-and-scope)

I have begun doing some testing to implement this feature by starting with `Bridge.js`

```js
function goToID(id){
    var el = document.getElementById(id);
    document.body.scrollTop = el.offsetTop - 20
    return el;
}

function removeAudioMark(){
    var els = document.body.getElementsByClassName("audio-mark")
    if( els.length > 0 )
    for( i = 0; i <= els.length; i++){
        els[i].classList.remove("audio-mark");
    }
}

function audioMarkID(id){
    removeAudioMark();
    var el = goToID(id);
    el.classList.add("audio-mark")
}
```

```css
.audio-mark {
    background: #81D4FA;
    border-radius: 3px;
    padding-right: 4px;
    margin-right: -4px
}
```
